import { Badge, Card, PageHeader } from "@/components/ui";
import { createMatchAction, createObservationAction } from "@/app/actions";
import { listMatches, listObservations, listPlayers, listSkills } from "@/repositories/postgres";

export const dynamic = "force-dynamic";
export default async function MatchesPage() {
  const [matches, observations, players, skills] = await Promise.all([listMatches(), listObservations(), listPlayers(), listSkills()]);
  return <div className="page"><PageHeader eyebrow="MATCH → TRÄNING" title="Matchobservationer"><details className="create-panel"><summary className="button primary">+ Ny match</summary><form action={createMatchAction} className="edit-form"><input name="opponent" placeholder="Motståndare" required/><input name="startsAt" type="datetime-local" required/><input name="location" placeholder="Plats"/><select name="gameFormat" defaultValue="7v7"><option>5v5</option><option>7v7</option><option>9v9</option><option>11v11</option></select><input name="result" placeholder="Resultat (frivilligt)"/><button className="button primary">Spara match</button></form></details></PageHeader>
    <div className="grid two"><Card title="Ny observation" meta="Gör matchen till nästa träningsfokus"><form action={createObservationAction} className="stack"><select name="matchId" required defaultValue=""><option value="" disabled>Välj match</option>{matches.map(m => <option key={m.id} value={m.id}>{m.opponent} · {new Date(m.startsAt).toLocaleDateString("sv-SE")}</option>)}</select><select name="sentiment" defaultValue="develop"><option value="develop">Behöver utvecklas</option><option value="positive">Positivt</option><option value="neutral">Neutralt</option></select><select name="playerId" defaultValue=""><option value="">Hela laget</option>{players.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><textarea name="summary" placeholder="Vad såg vi, utan att värdera spelaren?" required minLength={4}/><fieldset><legend>Färdigheter</legend><div className="tags">{skills.map(s => <label key={s.id}><input type="checkbox" name="skillIds" value={s.id}/> {s.name}</label>)}</div></fieldset><label><input type="checkbox" name="priority"/> Prioriterat träningsfokus</label><button className="button primary">Spara observation</button></form></Card><Card title="Arbetsflöde" meta="Från observation till uppföljning"><div className="flow"><b>Observation</b><span>→</span><b>Färdighet</b><span>→</span><b>Övningar</b><span>→</span><b>Träningspass</b><span>→</span><b>Uppföljning</b></div><p>Välj ett begränsat fokus, följ upp det i nästa träning och skapa vid behov ett individuellt mål under Spelare.</p></Card></div>
    <div className="grid two">{observations.map(o => <Card key={o.id} title={o.match} meta={o.createdAt.slice(0,10)}><Badge tone={o.sentiment === "positive" ? "green" : o.sentiment === "develop" ? "amber" : "blue"}>{o.sentiment === "positive" ? "POSITIVT" : o.sentiment === "develop" ? "BEHÖVER UTVECKLAS" : "NEUTRALT"}</Badge><p className="quote">“{o.summary}”</p>{o.playerId && <p>Individuell observation</p>}<div className="tags">{o.skillIds.map(id => <span key={id}>{skills.find(s => s.id === id)?.name ?? "Färdighet"}</span>)}</div></Card>)}</div>
  </div>;
}
