// Databaslager: Supabase (Postgres). Sätt DATABASE_URL i miljön.
//
// En enda postgres.js-anslutning, körd mot Supabase Transaction pooler
// (port 6543) – den stödjer inte prepared statements, därför `prepare: false`.
// Lågnivå-API:t (all/get/run/batch) tar SQL med ?-placeholders precis som
// tidigare mot Turso/libSQL, så actions.ts/queries.ts/live.ts är oförändrade.

import postgres from "postgres";
import { pendingSchemaMigrationIds } from "./schemaMigrations";

export type SqlArgs = (string | number | boolean | null)[];

// Standardfärger – enda källan för seed och återställning i inställningarna.
export const DEFAULT_COLORS: Record<string, string> = {
  primary_color: "#13306e",
  accent_color: "#ffd23f",
  jersey_color: "#ffd23f",
  jersey_text_color: "#111111",
  gk_jersey_color: "#1f9d57",
  gk_jersey_text_color: "#ffffff",
};

let sqlClient: ReturnType<typeof postgres> | null = null;

function getClient() {
  if (!sqlClient) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error("DATABASE_URL saknas i miljön");
    sqlClient = postgres(url, {
      prepare: false,
      // postgres.js returnerar bigint (SUM/COUNT av INTEGER, OID 20) som
      // sträng som default, eftersom värdet kan överstiga Number.MAX_SAFE_INTEGER.
      // Våra summor/counts/epoch-tider gör aldrig det, men koden adderar dem
      // med +, vilket annars blir strängsammanslagning i stället för addition.
      types: { bigint: { to: 20, from: [20], serialize: (x: number) => "" + x, parse: (x: string) => Number(x) } },
    });
  }
  return sqlClient;
}

// SQLite-stilen "?" → Postgres positionella "$1, $2, …".
function toPositional(sqlText: string): string {
  let i = 0;
  return sqlText.replace(/\?/g, () => `$${++i}`);
}

async function tryExec(sqlText: string) {
  try {
    await getClient().unsafe(sqlText);
  } catch (e) {
    // "column already exists" m.m. vid återkörda migrationer är förväntat
    const msg = e instanceof Error ? e.message : String(e);
    if (!/duplicate column|already exists/i.test(msg)) throw e;
  }
}

async function applyBaselineSchema(): Promise<void> {
  const tables = [
    `CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS players (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      jersey_number INTEGER,
      notes TEXT DEFAULT '',
      preferred_position_primary TEXT NOT NULL DEFAULT '',
      preferred_position_secondary TEXT NOT NULL DEFAULT '',
      preferred_level_primary TEXT NOT NULL DEFAULT '',
      preferred_level_secondary TEXT NOT NULL DEFAULT '',
      selection_eligible INTEGER NOT NULL DEFAULT 1,
      active INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS evaluations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      date TEXT NOT NULL,
      strengths TEXT DEFAULT '',
      development_goals TEXT DEFAULT '',
      coach_name TEXT DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS evaluation_scores (
      evaluation_id INTEGER NOT NULL REFERENCES evaluations(id) ON DELETE CASCADE,
      skill_id TEXT NOT NULL,
      level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 4),
      PRIMARY KEY (evaluation_id, skill_id)
    )`,
    `CREATE TABLE IF NOT EXISTS matches (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      opponent TEXT NOT NULL,
      home_away TEXT NOT NULL DEFAULT 'home',
      match_type TEXT NOT NULL DEFAULT 'seriespel',
      our_score INTEGER,
      opponent_score INTEGER,
      notes TEXT DEFAULT '',
      created_by_role TEXT DEFAULT 'coach',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS match_players (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      minutes INTEGER NOT NULL DEFAULT 0,
      goals INTEGER NOT NULL DEFAULT 0,
      assists INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS match_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER REFERENCES players(id) ON DELETE CASCADE,
      stat_id TEXT NOT NULL,
      match_second INTEGER,
      period INTEGER,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE INDEX IF NOT EXISTS idx_match_events_match ON match_events(match_id)`,
    `CREATE TABLE IF NOT EXISTS match_reporters (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      stats TEXT NOT NULL DEFAULT '[]',
      UNIQUE(match_id, name)
    )`,
    `CREATE TABLE IF NOT EXISTS live_rate_limits (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      reporter_key TEXT NOT NULL,
      window_start BIGINT NOT NULL,
      event_count INTEGER NOT NULL,
      PRIMARY KEY(match_id, reporter_key)
    )`,
    `CREATE TABLE IF NOT EXISTS match_squad (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS match_lineup (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      x REAL NOT NULL,
      y REAL NOT NULL,
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS match_subs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      off_player INTEGER REFERENCES players(id) ON DELETE SET NULL,
      on_player INTEGER REFERENCES players(id) ON DELETE SET NULL,
      match_second INTEGER,
      period INTEGER,
      created_at INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS player_self_evals (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      fun_rating INTEGER NOT NULL DEFAULT 2,
      progress_rating INTEGER NOT NULL DEFAULT 2,
      team_rating INTEGER NOT NULL DEFAULT 2,
      best_at TEXT NOT NULL DEFAULT '',
      want_to_improve TEXT NOT NULL DEFAULT '',
      note_to_coach TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS activity_log (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      coach_name TEXT NOT NULL,
      action TEXT NOT NULL,
      subject TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS login_throttle (
      ip TEXT PRIMARY KEY,
      fails INTEGER NOT NULL DEFAULT 0,
      window_start INTEGER NOT NULL DEFAULT 0,
      blocked_until INTEGER NOT NULL DEFAULT 0
    )`,
    // Matchbetyg (ELO-form): ett betyg per spelare/match. overall = "mot
    // förväntan"-stegets nyckel, scores = JSON med ev. områdesbetyg (avancerat),
    // suggested = appens förslag, delta = form-förändringen. Se lib/rating.ts.
    `CREATE TABLE IF NOT EXISTS match_ratings (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      overall TEXT NOT NULL,
      scores TEXT NOT NULL DEFAULT '{}',
      suggested TEXT NOT NULL DEFAULT '',
      delta INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL DEFAULT '',
      active INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS user_roles (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      role TEXT NOT NULL CHECK (role IN ('admin', 'head_coach', 'coach', 'leader', 'player', 'parent')),
      PRIMARY KEY (user_id, role)
    )`,
    `CREATE TABLE IF NOT EXISTS user_permissions (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      permission_key TEXT NOT NULL,
      allowed INTEGER NOT NULL DEFAULT 1,
      PRIMARY KEY (user_id, permission_key)
    )`,
    `CREATE TABLE IF NOT EXISTS groups (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      group_type TEXT NOT NULL CHECK (group_type IN ('squad', 'subgroup', 'matchgroup')),
      parent_id INTEGER REFERENCES groups(id) ON DELETE SET NULL,
      cup_name TEXT NOT NULL DEFAULT '',
      color TEXT NOT NULL DEFAULT '',
      active INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS player_group_memberships (
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
      is_primary INTEGER NOT NULL DEFAULT 0,
      starts_on TEXT,
      ends_on TEXT,
      PRIMARY KEY (player_id, group_id)
    )`,
    `CREATE TABLE IF NOT EXISTS user_group_access (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
      PRIMARY KEY (user_id, group_id)
    )`,
    `CREATE TABLE IF NOT EXISTS user_player_links (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      relation TEXT NOT NULL CHECK (relation IN ('self', 'parent')),
      PRIMARY KEY (user_id, player_id, relation)
    )`,
    `CREATE TABLE IF NOT EXISTS attendance_imports (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      source_type TEXT NOT NULL DEFAULT 'svenskalag_xlsx',
      file_name TEXT NOT NULL DEFAULT '',
      period_label TEXT NOT NULL DEFAULT '',
      team_name TEXT NOT NULL DEFAULT '',
      exported_at TEXT,
      imported_by TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS attendance_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      import_id INTEGER NOT NULL REFERENCES attendance_imports(id) ON DELETE CASCADE,
      player_id INTEGER REFERENCES players(id) ON DELETE SET NULL,
      player_name TEXT NOT NULL,
      birth_date TEXT,
      activity_date TEXT,
      start_time TEXT,
      end_time TEXT,
      title TEXT NOT NULL DEFAULT '',
      category TEXT NOT NULL DEFAULT 'other',
      source_column INTEGER NOT NULL DEFAULT 0,
      source_label TEXT NOT NULL DEFAULT '',
      present INTEGER NOT NULL DEFAULT 0 CHECK (present IN (0, 1))
    )`,
    `CREATE TABLE IF NOT EXISTS player_competition_match_counts (
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      season INTEGER NOT NULL,
      competition TEXT NOT NULL,
      source_team TEXT NOT NULL,
      match_count INTEGER NOT NULL DEFAULT 0 CHECK (match_count >= 0),
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      PRIMARY KEY (player_id, season, competition, source_team)
    )`,
    `CREATE TABLE IF NOT EXISTS player_competition_matches (
      external_id TEXT PRIMARY KEY,
      season INTEGER NOT NULL,
      competition TEXT NOT NULL,
      source_team TEXT NOT NULL,
      level INTEGER,
      match_date TEXT NOT NULL,
      start_time TEXT,
      opponent TEXT NOT NULL,
      home_away TEXT NOT NULL CHECK (home_away IN ('home', 'away')),
      location TEXT,
      source_url TEXT,
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS player_competition_match_players (
      match_external_id TEXT NOT NULL REFERENCES player_competition_matches(external_id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      PRIMARY KEY (match_external_id, player_id)
    )`,
    // Utvecklingsträdet (7v7 → 9v9): en rad per spelare/färdighet som klickas
    // i checklistan. skill_id pekar in i lib/skillTrappan.ts (statisk data, ingen tabell).
    `CREATE TABLE IF NOT EXISTS player_skill_status (
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      skill_id TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started', 'training', 'almost', 'done')),
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      PRIMARY KEY (player_id, skill_id)
    )`,
    `CREATE TABLE IF NOT EXISTS player_skill_notes (
      player_id INTEGER PRIMARY KEY REFERENCES players(id) ON DELETE CASCADE,
      note TEXT NOT NULL DEFAULT '',
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    // Daterade avstämningar är historiska ögonblicksbilder av utvecklingsträdet.
    // Det aktuella läget ligger fortsatt i player_skill_status för snabba ändringar.
    `CREATE TABLE IF NOT EXISTS development_checkpoints (
      id TEXT PRIMARY KEY,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      date TEXT NOT NULL,
      coach_name TEXT NOT NULL DEFAULT '',
      strengths TEXT NOT NULL DEFAULT '',
      focus_note TEXT NOT NULL DEFAULT '',
      wellbeing_note TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS development_checkpoint_skills (
      checkpoint_id TEXT NOT NULL REFERENCES development_checkpoints(id) ON DELETE CASCADE,
      skill_id TEXT NOT NULL,
      status TEXT NOT NULL CHECK (status IN ('not_started', 'training', 'almost', 'done')),
      previous_status TEXT NOT NULL CHECK (previous_status IN ('not_started', 'training', 'almost', 'done')),
      is_focus INTEGER NOT NULL DEFAULT 0 CHECK (is_focus IN (0, 1)),
      PRIMARY KEY (checkpoint_id, skill_id)
    )`,
    `CREATE TABLE IF NOT EXISTS development_activities (
      id TEXT PRIMARY KEY,
      activity_date TEXT NOT NULL,
      start_time TEXT,
      activity_type TEXT NOT NULL CHECK (activity_type IN ('training', 'match', 'other')),
      title TEXT NOT NULL,
      external_source TEXT NOT NULL DEFAULT 'manual',
      external_key TEXT NOT NULL UNIQUE,
      match_id INTEGER REFERENCES matches(id) ON DELETE SET NULL,
      group_id INTEGER REFERENCES groups(id) ON DELETE SET NULL,
      theme TEXT NOT NULL DEFAULT '',
      challenge_context TEXT NOT NULL DEFAULT 'balanced' CHECK (challenge_context IN ('safe', 'balanced', 'challenging')),
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS player_development_goals (
      id TEXT PRIMARY KEY,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      slot INTEGER NOT NULL CHECK (slot IN (1, 2)),
      title TEXT NOT NULL,
      evidence_hint TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'achieved', 'paused')),
      starts_on TEXT NOT NULL,
      review_on TEXT,
      ended_on TEXT,
      created_by TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS development_activity_participation (
      activity_id TEXT NOT NULL REFERENCES development_activities(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      attendance_status TEXT NOT NULL DEFAULT 'unknown' CHECK (attendance_status IN ('unknown', 'present', 'absent')),
      selected INTEGER NOT NULL DEFAULT 0 CHECK (selected IN (0, 1)),
      periods_played INTEGER NOT NULL DEFAULT 0 CHECK (periods_played >= 0 AND periods_played <= 9),
      position TEXT NOT NULL DEFAULT '',
      source TEXT NOT NULL DEFAULT 'manual',
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      PRIMARY KEY (activity_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS development_activity_callup_summaries (
      activity_id TEXT PRIMARY KEY REFERENCES development_activities(id) ON DELETE CASCADE,
      accepted_count INTEGER NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
      declined_count INTEGER NOT NULL DEFAULT 0 CHECK (declined_count >= 0),
      pending_count INTEGER NOT NULL DEFAULT 0 CHECK (pending_count >= 0),
      source TEXT NOT NULL DEFAULT 'svenskalag_callup',
      updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS development_activity_callups (
      activity_id TEXT NOT NULL REFERENCES development_activities(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      attendance_status TEXT NOT NULL DEFAULT 'unknown' CHECK (attendance_status IN ('unknown', 'present', 'absent')),
      PRIMARY KEY (activity_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS development_observations (
      id TEXT PRIMARY KEY,
      activity_id TEXT NOT NULL REFERENCES development_activities(id) ON DELETE CASCADE,
      player_id INTEGER REFERENCES players(id) ON DELETE CASCADE,
      goal_id TEXT REFERENCES player_development_goals(id) ON DELETE SET NULL,
      evidence TEXT NOT NULL CHECK (evidence IN ('shown', 'practicing', 'revisit')),
      note TEXT NOT NULL DEFAULT '',
      coach_name TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS development_selection_decisions (
      activity_id TEXT NOT NULL REFERENCES development_activities(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      decision TEXT NOT NULL CHECK (decision IN ('selected', 'reserve', 'rested')),
      rationale TEXT NOT NULL DEFAULT '',
      decided_by TEXT NOT NULL DEFAULT '',
      decided_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      PRIMARY KEY (activity_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS development_pilot_events (
      id TEXT PRIMARY KEY,
      event_type TEXT NOT NULL CHECK (event_type IN ('source_sync', 'goal_saved', 'observation_saved', 'selection_saved')),
      activity_id TEXT REFERENCES development_activities(id) ON DELETE SET NULL,
      duration_seconds INTEGER,
      item_count INTEGER NOT NULL DEFAULT 1,
      actor TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
  ];
  for (const sql of tables) await getClient().unsafe(sql);

  // Migrationer – körs om utan att fela på redan gjorda ändringar
  const migrations = [
    `ALTER TABLE match_players ADD COLUMN shots INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN shots_on_target INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN passes_completed INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN interceptions INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN saves INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN code TEXT`,
    `ALTER TABLE matches ADD COLUMN source TEXT NOT NULL DEFAULT 'manual'`,
    `ALTER TABLE matches ADD COLUMN external_uid TEXT`,
    `ALTER TABLE matches ADD COLUMN clock_started_at INTEGER`,
    `ALTER TABLE matches ADD COLUMN clock_offset INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN clock_running INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN clock_period INTEGER NOT NULL DEFAULT 1`,
    `ALTER TABLE match_events ADD COLUMN period INTEGER`,
    `ALTER TABLE matches ADD COLUMN start_time TEXT`,
    `ALTER TABLE matches ADD COLUMN periods INTEGER NOT NULL DEFAULT 3`,
    `ALTER TABLE matches ADD COLUMN period_minutes INTEGER NOT NULL DEFAULT 20`,
    `ALTER TABLE matches ADD COLUMN finished INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_events ADD COLUMN created_at INTEGER`,
    `ALTER TABLE match_reporters ADD COLUMN last_seen INTEGER`,
    `ALTER TABLE players ADD COLUMN position TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE players ADD COLUMN preferred_position_primary TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE players ADD COLUMN preferred_position_secondary TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE players ADD COLUMN preferred_level_primary TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE players ADD COLUMN preferred_level_secondary TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE players ADD COLUMN selection_eligible INTEGER NOT NULL DEFAULT 1`,
    `WITH first_run AS (
       INSERT INTO settings (key, value)
       VALUES ('data-2026-08-19-elif-selection-availability', 'applied')
       ON CONFLICT (key) DO NOTHING
       RETURNING key
     )
     UPDATE players
     SET selection_eligible = 0
     WHERE lower(trim(name)) = 'elif basar'
       AND EXISTS (SELECT 1 FROM first_run)`,
    `WITH first_run AS (
       INSERT INTO settings (key, value)
       VALUES ('data-2026-08-19-emma-goalkeeper', 'applied')
       ON CONFLICT (key) DO NOTHING
       RETURNING key
     )
     UPDATE players
     SET preferred_position_primary = 'Målvakt'
     WHERE lower(trim(name)) = 'emma ulander'
       AND preferred_position_primary = ''
       AND EXISTS (SELECT 1 FROM first_run)`,
    `ALTER TABLE players ADD COLUMN share_token TEXT`,
    // BIGINT, inte INTEGER: share_expires lagrar Date.now() i millisekunder
    // (13 siffror), som svämmar över Postgres 32-bitars INTEGER.
    `ALTER TABLE players ADD COLUMN share_expires BIGINT`,
    `ALTER TABLE players ALTER COLUMN share_expires TYPE BIGINT`,
    `ALTER TABLE players ADD COLUMN level TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN level TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN cup_name TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN formation TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN cup_phase TEXT NOT NULL DEFAULT 'group'`,
    `ALTER TABLE matches ADD COLUMN cup_round TEXT`,
    `ALTER TABLE matches ADD COLUMN report_open INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN report_token TEXT`,
    `UPDATE matches SET report_token = replace(gen_random_uuid()::text, '-', '') WHERE report_token IS NULL`,
    `ALTER TABLE matches ALTER COLUMN report_token SET DEFAULT replace(gen_random_uuid()::text, '-', '')`,
    `ALTER TABLE matches ALTER COLUMN report_token SET NOT NULL`,
    `ALTER TABLE match_players ADD COLUMN yellow_card INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN red_card INTEGER NOT NULL DEFAULT 0`,
    // Vem som loggade händelsen – gör duplikatskyddet per rapportör så att två
    // personer kan räkna samma statistik (t.ex. mål) utan att blockera varandra.
    `ALTER TABLE match_events ADD COLUMN reporter TEXT`,
    // Lokal, slumpad webbläsaridentitet. Kräver inget konto men gör att en
    // föräldrarapportör bara kan ångra sina egna händelser.
    `ALTER TABLE match_events ADD COLUMN reporter_key TEXT`,
    // Klientgenererad idempotensnyckel per mutation. Null för äldre rader och
    // händelser utan nyckel. Det unika indexet (se nedan) gör att en offline-replay
    // inte dubbellagrar samma händelse när svaret tappades.
    `ALTER TABLE match_events ADD COLUMN idempotency_key TEXT`,
    `ALTER TABLE match_subs ADD COLUMN idempotency_key TEXT`,
    `ALTER TABLE players ADD COLUMN pin TEXT`,
    // Löpande form-tal (ELO) – NULL tills spelaren betygsatts första gången, då
    // det seedas från spelarens nivå. Se lib/rating.ts.
    `ALTER TABLE players ADD COLUMN form_rating INTEGER`,
    `ALTER TABLE matches ADD COLUMN cup_group TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN location TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN group_id INTEGER REFERENCES groups(id) ON DELETE SET NULL`,
  ];
  for (const sql of migrations) await tryExec(sql);

  // En kallelse och ett spelat matchdeltagande är två separata fakta. Äldre
  // kallelser låg i deltagandetabellen och kunde därför skriva över historiken.
  await tryExec(`
    INSERT INTO development_activity_callups (activity_id, player_id, attendance_status)
    SELECT activity_id, player_id, attendance_status
    FROM development_activity_participation
    WHERE source = 'svenskalag_callup' AND selected = 1
    ON CONFLICT (activity_id, player_id) DO UPDATE
      SET attendance_status = excluded.attendance_status
  `);
  await tryExec(`DELETE FROM development_activity_participation WHERE source = 'svenskalag_callup'`);

  await tryExec(`CREATE INDEX IF NOT EXISTS idx_memberships_group ON player_group_memberships(group_id)`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_user_group_access_group ON user_group_access(group_id)`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_match_events_reporter ON match_events(match_id, reporter_key, id DESC)`);
  // Idempotens: en klientgenererad nyckel får bara finnas en gång per match.
  // Postgres behandlar NULL som distinkt i unika index, så äldre rader och
  // händelser utan nyckel krockar inte med varandra.
  await tryExec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_match_events_idem ON match_events(match_id, idempotency_key)`);
  await tryExec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_match_subs_idem ON match_subs(match_id, idempotency_key)`);
  await tryExec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_matches_report_token ON matches(report_token)`);
  await tryExec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_groups_identity ON groups(group_type, lower(name), COALESCE(parent_id, 0), lower(cup_name))`);

  await tryExec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_matches_code ON matches(code) WHERE code IS NOT NULL`
  );
  await tryExec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_players_token ON players(share_token) WHERE share_token IS NOT NULL`
  );
  await tryExec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_matches_uid ON matches(external_uid) WHERE external_uid IS NOT NULL`
  );
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_attendance_events_import_player ON attendance_events(import_id, player_id)`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_attendance_events_import_name ON attendance_events(import_id, lower(player_name))`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_attendance_events_import_date ON attendance_events(import_id, activity_date)`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_development_checkpoints_player_date ON development_checkpoints(player_id, date DESC, created_at DESC)`);
  await tryExec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_development_goals_active_slot ON player_development_goals(player_id, slot) WHERE status = 'active'`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_development_goals_player ON player_development_goals(player_id, status, starts_on DESC)`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_development_activities_date ON development_activities(activity_date DESC, start_time DESC)`);
  await tryExec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_development_activities_match ON development_activities(match_id) WHERE match_id IS NOT NULL`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_development_observations_player ON development_observations(player_id, created_at DESC)`);
  await tryExec(`CREATE INDEX IF NOT EXISTS idx_development_observations_activity ON development_observations(activity_id, created_at DESC)`);

  // Befintliga Svenska Lag-källor blir kontext i den nya kärnan. Ingen kalender,
  // match eller närvaro kopieras till en ny sanningskälla; raderna nedan är
  // stabila referenser som kan kompletteras med tema, observation och uttagning.
  await getClient().unsafe(`
    INSERT INTO development_activities (
      id, activity_date, start_time, activity_type, title,
      external_source, external_key, match_id, group_id
    )
    SELECT
      'match-' || m.id::text,
      m.date,
      m.start_time,
      'match',
      CASE WHEN m.home_away = 'away' THEN 'Borta mot ' ELSE 'Hemma mot ' END || m.opponent,
      COALESCE(NULLIF(m.source, ''), 'match'),
      'match:' || m.id::text,
      m.id,
      m.group_id
    FROM matches m
    ON CONFLICT (external_key) DO UPDATE SET
      activity_date = excluded.activity_date,
      start_time = excluded.start_time,
      title = excluded.title,
      group_id = excluded.group_id,
      updated_at = to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
  `);
  await getClient().unsafe(`
    INSERT INTO development_activities (
      id, activity_date, start_time, activity_type, title,
      external_source, external_key
    )
    SELECT
      'svenskalag-' || md5(concat_ws('|', ae.activity_date, ae.start_time, ae.title, ae.category)),
      ae.activity_date,
      MIN(ae.start_time),
      CASE WHEN ae.category = 'training' THEN 'training'
           WHEN ae.category = 'match' THEN 'match'
           ELSE 'other' END,
      COALESCE(NULLIF(MAX(ae.title), ''), 'Aktivitet'),
      'svenskalag_attendance',
      'svenskalag:' || md5(concat_ws('|', ae.activity_date, ae.start_time, ae.title, ae.category))
    FROM attendance_events ae
    WHERE ae.import_id = (SELECT id FROM attendance_imports ORDER BY id DESC LIMIT 1)
      AND ae.activity_date IS NOT NULL
    GROUP BY ae.activity_date, ae.start_time, ae.title, ae.category
    ON CONFLICT (external_key) DO UPDATE SET
      activity_date = excluded.activity_date,
      start_time = excluded.start_time,
      activity_type = excluded.activity_type,
      title = excluded.title,
      updated_at = to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
  `);
  await getClient().unsafe(`
    INSERT INTO development_activities (
      id, activity_date, start_time, activity_type, title,
      external_source, external_key, group_id
    )
    SELECT
      'sanktan-' || pcm.external_id,
      pcm.match_date,
      pcm.start_time,
      'match',
      CASE WHEN pcm.home_away = 'away' THEN 'Borta mot ' ELSE 'Hemma mot ' END || pcm.opponent,
      'svenskalag_sanktan',
      'sanktan:' || pcm.external_id,
      g.id
    FROM player_competition_matches pcm
    LEFT JOIN groups g
      ON g.group_type = 'subgroup' AND g.active = 1 AND g.name = pcm.source_team
    WHERE pcm.competition = 'sanktan'
    ON CONFLICT (external_key) DO UPDATE SET
      activity_date = excluded.activity_date,
      start_time = excluded.start_time,
      activity_type = excluded.activity_type,
      title = excluded.title,
      group_id = excluded.group_id,
      updated_at = to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
  `);
  await getClient().unsafe(`
    INSERT INTO development_activity_participation (
      activity_id, player_id, attendance_status, selected, source
    )
    SELECT da.id, pcmp.player_id, 'present', 1, 'svenskalag_sanktan'
    FROM player_competition_match_players pcmp
    JOIN development_activities da
      ON da.external_key = 'sanktan:' || pcmp.match_external_id
    ON CONFLICT (activity_id, player_id) DO UPDATE SET
      attendance_status = 'present',
      selected = 1,
      source = 'svenskalag_sanktan',
      updated_at = to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
  `);
  await getClient().unsafe(`
    INSERT INTO development_activity_participation (
      activity_id, player_id, attendance_status, source
    )
    SELECT
      da.id,
      ae.player_id,
      CASE WHEN MAX(ae.present) = 1 THEN 'present' ELSE 'absent' END,
      'svenskalag_attendance'
    FROM attendance_events ae
    JOIN development_activities da
      ON da.external_key = 'svenskalag:' || md5(concat_ws('|', ae.activity_date, ae.start_time, ae.title, ae.category))
    WHERE ae.import_id = (SELECT id FROM attendance_imports ORDER BY id DESC LIMIT 1)
      AND ae.player_id IS NOT NULL
    GROUP BY da.id, ae.player_id
    ON CONFLICT (activity_id, player_id) DO UPDATE SET
      attendance_status = excluded.attendance_status,
      source = excluded.source,
      updated_at = to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
  `);
  await getClient().unsafe(`
    INSERT INTO development_activity_participation (
      activity_id, player_id, attendance_status, selected, periods_played, source
    )
    SELECT da.id, mp.player_id, 'present', 1, 0, 'legacy_match'
    FROM match_players mp
    JOIN development_activities da ON da.match_id = mp.match_id
    ON CONFLICT (activity_id, player_id) DO UPDATE SET
      attendance_status = 'present',
      selected = 1,
      source = CASE
        WHEN development_activity_participation.source = 'manual' THEN development_activity_participation.source
        ELSE excluded.source
      END,
      updated_at = to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
  `);

  // Seed – inställningar
  // Datamigrationer ovan kan redan ha lagt egna settings-nycklar även på en
  // tom databas. Seeda därför varje standardnyckel individuellt.
  const defaults: [string, string][] = [
    ["club_name", "Bollstanäs SK"],
    ["team_name", "BSK F2014"],
    ["birth_year", "2014"],
    ["primary_color", DEFAULT_COLORS.primary_color],
    ["accent_color", DEFAULT_COLORS.accent_color],
    ["coach_code", "TRANARE2014"],
    ["season", "2026"],
  ];
  for (const [k, v] of defaults) {
    await getClient().unsafe(
      "INSERT INTO settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING",
      [k, v]
    );
  }
  await getClient().unsafe(
    "INSERT INTO settings (key, value) VALUES ('calendar_url', '') ON CONFLICT (key) DO NOTHING"
  );
  await getClient().unsafe(
    "INSERT INTO settings (key, value) VALUES ('allowed_coach_emails', '') ON CONFLICT (key) DO NOTHING"
  );
  // Matchtröjefärger – seedas för redan installerade appar utan att skriva över
  const jerseyDefaults: [string, string][] = [
    ["jersey_color", DEFAULT_COLORS.jersey_color],
    ["jersey_text_color", DEFAULT_COLORS.jersey_text_color],
    ["gk_jersey_color", DEFAULT_COLORS.gk_jersey_color],
    ["gk_jersey_text_color", DEFAULT_COLORS.gk_jersey_text_color],
  ];
  for (const [k, v] of jerseyDefaults) {
    await getClient().unsafe(
      "INSERT INTO settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING",
      [k, v]
    );
  }

  // Migrera den befintliga, odelade truppen till en huvudtrupp + standardundergrupp.
  // Medlemskap är många-till-många så samma spelare kan senare ligga i flera
  // undergrupper och tillfälliga cup-/matchgrupper utan att historik skrivs om.
  const teamNameRow = await getClient().unsafe("SELECT value FROM settings WHERE key = 'team_name'");
  const teamName = String(teamNameRow[0]?.value || "BSK F2014");
  const squadRows = await getClient().unsafe(
    "INSERT INTO groups (name, group_type) SELECT $1, 'squad' WHERE NOT EXISTS (SELECT 1 FROM groups WHERE group_type = 'squad') ON CONFLICT DO NOTHING RETURNING id",
    [teamName]
  );
  const existingSquad = squadRows[0] ?? (await getClient().unsafe("SELECT id FROM groups WHERE group_type = 'squad' ORDER BY id LIMIT 1"))[0];
  if (existingSquad?.id) {
    const subgroupRows = await getClient().unsafe(
      "INSERT INTO groups (name, group_type, parent_id, color) SELECT 'Gul', 'subgroup', $1, $2 WHERE NOT EXISTS (SELECT 1 FROM groups WHERE group_type = 'subgroup') ON CONFLICT DO NOTHING RETURNING id",
      [existingSquad.id, DEFAULT_COLORS.accent_color]
    );
    const subgroup = subgroupRows[0] ?? (await getClient().unsafe("SELECT id FROM groups WHERE group_type = 'subgroup' ORDER BY id LIMIT 1"))[0];
    if (subgroup?.id) {
      // Lägg hela den odelade truppen i standardgruppen endast när gruppen
      // faktiskt skapas första gången. Vid senare schemaändringar finns gruppen
      // redan och befintliga Gul/Grön/F15-medlemskap får aldrig skrivas över.
      if (subgroupRows[0]?.id) {
        await getClient().unsafe(
          "INSERT INTO player_group_memberships (player_id, group_id, is_primary) SELECT id, $1, 1 FROM players ON CONFLICT DO NOTHING",
          [subgroup.id]
        );
      }
      await getClient().unsafe("UPDATE matches SET group_id = $1 WHERE group_id IS NULL", [subgroup.id]);
    }
  }

  // Seed – exempelspelare
  const playerCount = await getClient().unsafe("SELECT COUNT(*) AS c FROM players");
  if (Number(playerCount[0].c) === 0) {
    const demo = [
      "Exempel: Alva", "Exempel: Ebba", "Exempel: Elsa", "Exempel: Freja",
      "Exempel: Lilly", "Exempel: Maja", "Exempel: Nora", "Exempel: Saga",
      "Exempel: Stella", "Exempel: Vera",
    ];
    for (let i = 0; i < demo.length; i++) {
      await getClient().unsafe(
        "INSERT INTO players (name, jersey_number) VALUES ($1, $2)",
        [demo[i], i + 2]
      );
    }
  }

  const defaultSubgroup = (await getClient().unsafe(
    "SELECT id FROM groups WHERE group_type = 'subgroup' AND active = 1 ORDER BY id LIMIT 1"
  ))[0];
  if (defaultSubgroup?.id) {
    await getClient().unsafe(
      `INSERT INTO player_group_memberships (player_id, group_id, is_primary)
       SELECT p.id, $1, 1 FROM players p
       WHERE NOT EXISTS (SELECT 1 FROM player_group_memberships pgm WHERE pgm.player_id = p.id)
       ON CONFLICT DO NOTHING`,
      [defaultSubgroup.id]
    );
  }

}

type SchemaMigration = {
  id: string;
  run: () => Promise<void>;
};

async function markSoleSubgroupMembershipsPrimary(): Promise<void> {
  await getClient().unsafe(`
    UPDATE player_group_memberships pgm
    SET is_primary = 1
    FROM groups g
    WHERE pgm.group_id = g.id
      AND g.group_type = 'subgroup'
      AND g.active = 1
      AND pgm.player_id IN (
        SELECT sole.player_id
        FROM player_group_memberships sole
        JOIN groups sole_group ON sole_group.id = sole.group_id
        WHERE sole_group.group_type = 'subgroup' AND sole_group.active = 1
        GROUP BY sole.player_id
        HAVING COUNT(*) = 1
      )
  `);
}

// Lägg aldrig ny DDL i baslinjen för en redan driftsatt installation. Lägg i
// stället till en ny post sist i listan. Varje id journalförs efter lyckad körning.
const SCHEMA_MIGRATIONS: readonly SchemaMigration[] = [
  { id: "0001-baseline-2026-08-20", run: applyBaselineSchema },
  { id: "0002-primary-subgroup-memberships", run: markSoleSubgroupMembershipsPrimary },
  { id: "0003-match-evaluations", run: async () => {
    await getClient().unsafe(`CREATE TABLE IF NOT EXISTS match_evaluation_invites (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      label TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL,
      revoked_at TIMESTAMPTZ, created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )`);
    await getClient().unsafe(`CREATE TABLE IF NOT EXISTS match_player_evaluations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      contributor_type TEXT NOT NULL CHECK (contributor_type IN ('coach', 'invite')),
      contributor_id TEXT NOT NULL,
      self_comparison TEXT NOT NULL CHECK (self_comparison IN ('below', 'usual', 'above')),
      match_impact TEXT NOT NULL CHECK (match_impact IN ('struggled', 'held', 'influenced')),
      reason_tag TEXT NOT NULL DEFAULT '', player_level_snapshot TEXT NOT NULL DEFAULT '',
      match_level_snapshot TEXT NOT NULL DEFAULT '', created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      UNIQUE(match_id, player_id, contributor_type, contributor_id)
    )`);
    await getClient().unsafe("CREATE INDEX IF NOT EXISTS idx_match_evaluations_player ON match_player_evaluations(player_id, match_id)");
    await getClient().unsafe("DROP TABLE IF EXISTS match_ratings");
    await getClient().unsafe("ALTER TABLE players DROP COLUMN IF EXISTS form_rating");
  } },
  { id: "0004-mobile-auth", run: async () => {
    await getClient().unsafe(`CREATE TABLE IF NOT EXISTS mobile_oauth_states (
      state_hash TEXT PRIMARY KEY,
      code_challenge TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      expires_at TIMESTAMPTZ NOT NULL,
      consumed_at TIMESTAMPTZ
    )`);
    await getClient().unsafe(`CREATE TABLE IF NOT EXISTS mobile_auth_codes (
      code_hash TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      code_challenge TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      expires_at TIMESTAMPTZ NOT NULL,
      consumed_at TIMESTAMPTZ
    )`);
    await getClient().unsafe(`CREATE TABLE IF NOT EXISTS mobile_device_sessions (
      id UUID PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      device_id UUID NOT NULL,
      device_name TEXT NOT NULL DEFAULT '',
      access_token_hash TEXT NOT NULL UNIQUE,
      access_expires_at TIMESTAMPTZ NOT NULL,
      refresh_token_hash TEXT NOT NULL UNIQUE,
      previous_refresh_token_hash TEXT,
      refresh_expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      last_used_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      revoked_at TIMESTAMPTZ,
      UNIQUE(user_id, device_id)
    )`);
    await getClient().unsafe("CREATE INDEX IF NOT EXISTS idx_mobile_oauth_states_expiry ON mobile_oauth_states(expires_at)");
    await getClient().unsafe("CREATE INDEX IF NOT EXISTS idx_mobile_auth_codes_expiry ON mobile_auth_codes(expires_at)");
    await getClient().unsafe("CREATE INDEX IF NOT EXISTS idx_mobile_device_sessions_user ON mobile_device_sessions(user_id, revoked_at)");
    await getClient().unsafe("CREATE INDEX IF NOT EXISTS idx_mobile_device_sessions_previous_refresh ON mobile_device_sessions(previous_refresh_token_hash)");
  } },
  { id: "0005-sanktan-evaluation-bridge", run: async () => {
    const yellowGroup = (await getClient().unsafe(
      "SELECT id FROM groups WHERE group_type = 'subgroup' AND active = 1 AND name = 'Gul' ORDER BY id LIMIT 1"
    ))[0];
    if (!yellowGroup?.id) return;

    // Sanktan är kalenderns sanningskälla. Återanvänd en redan importerad match
    // när datum, tid och motståndare stämmer; skapa bara de rader som saknas.
    await getClient().unsafe(`
      INSERT INTO matches (
        date, start_time, opponent, home_away, match_type, level, location,
        group_id, source, external_uid
      )
      SELECT pcm.match_date, pcm.start_time, pcm.opponent, pcm.home_away,
             'seriespel', pcm.level::text, COALESCE(pcm.location, ''),
             $1, 'svenskalag_sanktan', 'sanktan:' || pcm.external_id
      FROM player_competition_matches pcm
      WHERE pcm.competition = 'sanktan' AND pcm.source_team = 'Gul'
        AND NOT EXISTS (
          SELECT 1 FROM matches existing
          WHERE existing.date = pcm.match_date
            AND COALESCE(existing.start_time, '') = COALESCE(pcm.start_time, '')
            AND lower(regexp_replace(existing.opponent, '^mot[[:space:]]+', '', 'i')) = lower(pcm.opponent)
        )
      ON CONFLICT (external_uid) WHERE external_uid IS NOT NULL DO UPDATE SET
        date = excluded.date, start_time = excluded.start_time,
        opponent = excluded.opponent, home_away = excluded.home_away,
        level = excluded.level, location = excluded.location, group_id = excluded.group_id
    `, [yellowGroup.id]);

    // En äldre matchimport kan redan ha skapat en generell matchaktivitet med
    // samma match_id. Sanktanaktiviteten är den kanoniska aktiviteten i det här
    // flödet, så frigör länken innan den flyttas dit. Själva äldre aktiviteten
    // behålls för historik men pekar inte längre på matchen.
    await getClient().unsafe(`
      UPDATE development_activities legacy_activity
      SET match_id = NULL
      FROM player_competition_matches pcm
      CROSS JOIN LATERAL (
        SELECT m.id
        FROM matches m
        WHERE m.external_uid = 'sanktan:' || pcm.external_id
           OR (
             m.date = pcm.match_date
             AND COALESCE(m.start_time, '') = COALESCE(pcm.start_time, '')
             AND lower(regexp_replace(m.opponent, '^mot[[:space:]]+', '', 'i')) = lower(pcm.opponent)
           )
        ORDER BY CASE WHEN m.external_uid = 'sanktan:' || pcm.external_id THEN 0 ELSE 1 END, m.id
        LIMIT 1
      ) linked
      WHERE legacy_activity.match_id = linked.id
        AND legacy_activity.external_key <> 'sanktan:' || pcm.external_id
        AND pcm.competition = 'sanktan' AND pcm.source_team = 'Gul'
    `);

    await getClient().unsafe(`
      UPDATE development_activities da
      SET match_id = linked.id
      FROM player_competition_matches pcm
      CROSS JOIN LATERAL (
        SELECT m.id
        FROM matches m
        WHERE m.external_uid = 'sanktan:' || pcm.external_id
           OR (
             m.date = pcm.match_date
             AND COALESCE(m.start_time, '') = COALESCE(pcm.start_time, '')
             AND lower(regexp_replace(m.opponent, '^mot[[:space:]]+', '', 'i')) = lower(pcm.opponent)
           )
        ORDER BY CASE WHEN m.external_uid = 'sanktan:' || pcm.external_id THEN 0 ELSE 1 END, m.id
        LIMIT 1
      ) linked
      WHERE da.external_key = 'sanktan:' || pcm.external_id
        AND pcm.competition = 'sanktan' AND pcm.source_team = 'Gul'
    `);

    // Äldre sparade uttagningar blir direkt användbara i utvärderingen.
    await getClient().unsafe(`
      INSERT INTO match_squad (match_id, player_id)
      SELECT da.match_id, sd.player_id
      FROM development_selection_decisions sd
      JOIN development_activities da ON da.id = sd.activity_id
      WHERE da.match_id IS NOT NULL AND sd.decision = 'selected'
      ON CONFLICT DO NOTHING
    `);
  } },
  { id: "0006-skippable-match-evaluations", run: async () => {
    await getClient().unsafe("ALTER TABLE match_player_evaluations ALTER COLUMN self_comparison DROP NOT NULL");
    await getClient().unsafe("ALTER TABLE match_player_evaluations ALTER COLUMN match_impact DROP NOT NULL");
    await getClient().unsafe("ALTER TABLE match_player_evaluations ADD COLUMN IF NOT EXISTS skipped INTEGER NOT NULL DEFAULT 0");
  } },
];
const LEGACY_BASELINE_VERSION = "2026-08-19-sanktan-callups-v4";
const MIGRATION_LOCK_KEYS = [118119812, 2014] as const;

async function init(): Promise<void> {
  // Normal kallstart gör bara en billig läsning. Tabellen skapas enbart vid
  // första starten; IF NOT EXISTS gör den samtidighetssäker före låsningen.
  try {
    await getClient().unsafe("SELECT 1 FROM schema_migrations LIMIT 1");
  } catch (error) {
    if (!(error && typeof error === "object" && "code" in error && error.code === "42P01")) throw error;
    await getClient().unsafe(`CREATE TABLE IF NOT EXISTS schema_migrations (
      id TEXT PRIMARY KEY,
      applied_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`);
  }

  const lockConnection = await getClient().reserve();
  try {
    await lockConnection.unsafe("SELECT pg_advisory_lock($1, $2)", [...MIGRATION_LOCK_KEYS]);

    let appliedRows = await getClient().unsafe("SELECT id FROM schema_migrations ORDER BY id");
    const baselineId = SCHEMA_MIGRATIONS[0].id;
    if (!appliedRows.some((row) => row.id === baselineId)) {
      // Den befintliga produktionen hade redan hela baslinjen när journalen
      // infördes. Markera den utan att återköra äldre seed-/speglingsteg.
      let legacyVersion = "";
      try {
        const legacyRows = await getClient().unsafe("SELECT value FROM settings WHERE key = 'schema_version'");
        legacyVersion = String(legacyRows[0]?.value ?? "");
      } catch {
        // Tom databas saknar settings och ska därför köra baslinjen.
      }
      if (legacyVersion === LEGACY_BASELINE_VERSION) {
        await getClient().unsafe("INSERT INTO schema_migrations (id) VALUES ($1) ON CONFLICT DO NOTHING", [baselineId]);
        appliedRows = await getClient().unsafe("SELECT id FROM schema_migrations ORDER BY id");
      }
    }

    const appliedIds = new Set(appliedRows.map((row) => String(row.id)));
    for (const id of pendingSchemaMigrationIds(SCHEMA_MIGRATIONS.map((migration) => migration.id), appliedIds)) {
      const migration = SCHEMA_MIGRATIONS.find((candidate) => candidate.id === id);
      if (!migration) throw new Error(`Schemamigration saknas: ${id}`);
      await migration.run();
      await getClient().unsafe("INSERT INTO schema_migrations (id) VALUES ($1)", [migration.id]);
    }
  } finally {
    try {
      await lockConnection.unsafe("SELECT pg_advisory_unlock($1, $2)", [...MIGRATION_LOCK_KEYS]);
    } finally {
      await lockConnection.release();
    }
  }
}

let readyPromise: Promise<void> | null = null;
function ready(): Promise<void> {
  if (!readyPromise) readyPromise = init();
  return readyPromise;
}

// ---- Frågehjälpare ----

export async function all<T>(sqlText: string, args: SqlArgs = []): Promise<T[]> {
  await ready();
  const rows = await getClient().unsafe(toPositional(sqlText), args as never[]);
  return rows as unknown as T[];
}

export async function get<T>(sqlText: string, args: SqlArgs = []): Promise<T | undefined> {
  const rows = await all<T>(sqlText, args);
  return rows[0];
}

export async function run(sqlText: string, args: SqlArgs = []): Promise<Record<string, unknown>[]> {
  await ready();
  const rows = await getClient().unsafe(toPositional(sqlText), args as never[]);
  return rows as unknown as Record<string, unknown>[];
}

// Flera skrivningar i en transaktion
export async function batch(statements: { sql: string; args?: SqlArgs }[]): Promise<void> {
  await ready();
  if (statements.length === 0) return;
  await getClient().begin(async (tx) => {
    for (const s of statements) {
      await tx.unsafe(toPositional(s.sql), (s.args ?? []) as never[]);
    }
  });
}

// ---- Inställningar ----

export async function getSetting(key: string): Promise<string> {
  const row = await get<{ value: string }>("SELECT value FROM settings WHERE key = ?", [key]);
  return row?.value ?? "";
}

export async function setSetting(key: string, value: string): Promise<void> {
  await run(
    "INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    [key, value]
  );
}

export async function getAllSettings(): Promise<Record<string, string>> {
  const rows = await all<{ key: string; value: string }>("SELECT key, value FROM settings");
  return Object.fromEntries(rows.map((r) => [r.key, r.value]));
}

// ---- Aktivitetslogg ----

export type ActivityEntry = {
  id: number;
  coach_name: string;
  action: string;
  subject: string;
  created_at: string;
};

export async function logActivity(coachName: string, action: string, subject: string): Promise<void> {
  await run(
    "INSERT INTO activity_log (coach_name, action, subject) VALUES (?, ?, ?)",
    [coachName.slice(0, 60), action.slice(0, 80), subject.slice(0, 100)]
  );
}

export async function getRecentActivity(limit = 10): Promise<ActivityEntry[]> {
  return all<ActivityEntry>(
    "SELECT id, coach_name, action, subject, created_at FROM activity_log ORDER BY id DESC LIMIT ?",
    [limit]
  );
}
