// Databaslager: Supabase (Postgres). Sätt DATABASE_URL i miljön.
//
// En enda postgres.js-anslutning, körd mot Supabase Transaction pooler
// (port 6543) – den stödjer inte prepared statements, därför `prepare: false`.
// Lågnivå-API:t (all/get/run/batch) tar SQL med ?-placeholders precis som
// tidigare mot Turso/libSQL, så actions.ts/queries.ts/live.ts är oförändrade.

import postgres from "postgres";

export type SqlArgs = (string | number | boolean | null)[];

// Standardfärger – enda källan för seed och återställning i inställningarna.
export const DEFAULT_COLORS: Record<string, string> = {
  primary_color: "#13306e",
  accent_color: "#ffd23f",
  jersey_color: "#ffd23f",
  jersey_text_color: "#111111",
  gk_jersey_color: "#1f9d57",
  gk_jersey_text_color: "#ffffff",
};

let sqlClient: ReturnType<typeof postgres> | null = null;

function getClient() {
  if (!sqlClient) {
    const url = process.env.DATABASE_URL;
    if (!url) throw new Error("DATABASE_URL saknas i miljön");
    sqlClient = postgres(url, {
      prepare: false,
      // postgres.js returnerar bigint (SUM/COUNT av INTEGER, OID 20) som
      // sträng som default, eftersom värdet kan överstiga Number.MAX_SAFE_INTEGER.
      // Våra summor/counts/epoch-tider gör aldrig det, men koden adderar dem
      // med +, vilket annars blir strängsammanslagning i stället för addition.
      types: { bigint: { to: 20, from: [20], serialize: (x: number) => "" + x, parse: (x: string) => Number(x) } },
    });
  }
  return sqlClient;
}

// SQLite-stilen "?" → Postgres positionella "$1, $2, …".
function toPositional(sqlText: string): string {
  let i = 0;
  return sqlText.replace(/\?/g, () => `$${++i}`);
}

async function tryExec(sqlText: string) {
  try {
    await getClient().unsafe(sqlText);
  } catch (e) {
    // "column already exists" m.m. vid återkörda migrationer är förväntat
    const msg = e instanceof Error ? e.message : String(e);
    if (!/duplicate column|already exists/i.test(msg)) throw e;
  }
}

// Bumpa vid VARJE schemaändring nedan (ny tabell/kolumn/migration). Grinden
// nedan hoppar över all DDL när databasen redan är på denna version – annars
// körs ~40 sekventiella satser mot Postgres vid varje kall serverless-start.
const SCHEMA_VERSION = "2026-06-20b";

async function init(): Promise<void> {
  // Snabbväg: är schemat redan aktuellt? Hoppa över tabeller/migrationer/seed.
  // OBS: rå-klienten används här – get/all/run anropar ready() → init() (rekursion).
  try {
    const res = await getClient().unsafe(
      "SELECT value FROM settings WHERE key = 'schema_version'"
    );
    if (res[0]?.value === SCHEMA_VERSION) return;
  } catch {
    // settings-tabellen finns inte än (tom databas) – kör full init.
  }

  const tables = [
    `CREATE TABLE IF NOT EXISTS settings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS players (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      jersey_number INTEGER,
      notes TEXT DEFAULT '',
      active INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS evaluations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      date TEXT NOT NULL,
      strengths TEXT DEFAULT '',
      development_goals TEXT DEFAULT '',
      coach_name TEXT DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS evaluation_scores (
      evaluation_id INTEGER NOT NULL REFERENCES evaluations(id) ON DELETE CASCADE,
      skill_id TEXT NOT NULL,
      level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 4),
      PRIMARY KEY (evaluation_id, skill_id)
    )`,
    `CREATE TABLE IF NOT EXISTS matches (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date TEXT NOT NULL,
      opponent TEXT NOT NULL,
      home_away TEXT NOT NULL DEFAULT 'home',
      match_type TEXT NOT NULL DEFAULT 'seriespel',
      our_score INTEGER,
      opponent_score INTEGER,
      notes TEXT DEFAULT '',
      created_by_role TEXT DEFAULT 'coach',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS match_players (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      minutes INTEGER NOT NULL DEFAULT 0,
      goals INTEGER NOT NULL DEFAULT 0,
      assists INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS match_events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER REFERENCES players(id) ON DELETE CASCADE,
      stat_id TEXT NOT NULL,
      match_second INTEGER,
      period INTEGER,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE INDEX IF NOT EXISTS idx_match_events_match ON match_events(match_id)`,
    `CREATE TABLE IF NOT EXISTS match_reporters (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      stats TEXT NOT NULL DEFAULT '[]',
      UNIQUE(match_id, name)
    )`,
    `CREATE TABLE IF NOT EXISTS match_squad (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS match_lineup (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      x REAL NOT NULL,
      y REAL NOT NULL,
      PRIMARY KEY (match_id, player_id)
    )`,
    `CREATE TABLE IF NOT EXISTS match_subs (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      off_player INTEGER REFERENCES players(id) ON DELETE SET NULL,
      on_player INTEGER REFERENCES players(id) ON DELETE SET NULL,
      match_second INTEGER,
      period INTEGER,
      created_at INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS player_self_evals (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      fun_rating INTEGER NOT NULL DEFAULT 2,
      progress_rating INTEGER NOT NULL DEFAULT 2,
      team_rating INTEGER NOT NULL DEFAULT 2,
      best_at TEXT NOT NULL DEFAULT '',
      want_to_improve TEXT NOT NULL DEFAULT '',
      note_to_coach TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS player_interviews (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      player_name TEXT NOT NULL,
      position TEXT NOT NULL,
      summary TEXT NOT NULL DEFAULT '',
      messages TEXT NOT NULL DEFAULT '[]',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS activity_log (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      coach_name TEXT NOT NULL,
      action TEXT NOT NULL,
      subject TEXT NOT NULL DEFAULT '',
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')
    )`,
    `CREATE TABLE IF NOT EXISTS login_throttle (
      ip TEXT PRIMARY KEY,
      fails INTEGER NOT NULL DEFAULT 0,
      window_start INTEGER NOT NULL DEFAULT 0,
      blocked_until INTEGER NOT NULL DEFAULT 0
    )`,
    // Matchbetyg (ELO-form): ett betyg per spelare/match. overall = "mot
    // förväntan"-stegets nyckel, scores = JSON med ev. områdesbetyg (avancerat),
    // suggested = appens förslag, delta = form-förändringen. Se lib/rating.ts.
    `CREATE TABLE IF NOT EXISTS match_ratings (
      match_id INTEGER NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
      player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
      overall TEXT NOT NULL,
      scores TEXT NOT NULL DEFAULT '{}',
      suggested TEXT NOT NULL DEFAULT '',
      delta INTEGER NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS'),
      PRIMARY KEY (match_id, player_id)
    )`,
  ];
  for (const sql of tables) await getClient().unsafe(sql);

  // Migrationer – körs om utan att fela på redan gjorda ändringar
  const migrations = [
    `ALTER TABLE match_players ADD COLUMN shots INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN shots_on_target INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN passes_completed INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN interceptions INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN saves INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN code TEXT`,
    `ALTER TABLE matches ADD COLUMN source TEXT NOT NULL DEFAULT 'manual'`,
    `ALTER TABLE matches ADD COLUMN external_uid TEXT`,
    `ALTER TABLE matches ADD COLUMN clock_started_at INTEGER`,
    `ALTER TABLE matches ADD COLUMN clock_offset INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN clock_running INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE matches ADD COLUMN clock_period INTEGER NOT NULL DEFAULT 1`,
    `ALTER TABLE match_events ADD COLUMN period INTEGER`,
    `ALTER TABLE matches ADD COLUMN start_time TEXT`,
    `ALTER TABLE matches ADD COLUMN periods INTEGER NOT NULL DEFAULT 3`,
    `ALTER TABLE matches ADD COLUMN period_minutes INTEGER NOT NULL DEFAULT 20`,
    `ALTER TABLE matches ADD COLUMN finished INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_events ADD COLUMN created_at INTEGER`,
    `ALTER TABLE match_reporters ADD COLUMN last_seen INTEGER`,
    `ALTER TABLE players ADD COLUMN position TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE players ADD COLUMN share_token TEXT`,
    // BIGINT, inte INTEGER: share_expires lagrar Date.now() i millisekunder
    // (13 siffror), som svämmar över Postgres 32-bitars INTEGER.
    `ALTER TABLE players ADD COLUMN share_expires BIGINT`,
    `ALTER TABLE players ALTER COLUMN share_expires TYPE BIGINT`,
    `ALTER TABLE players ADD COLUMN share_summary TEXT`,
    `ALTER TABLE players ADD COLUMN level TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN level TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN cup_name TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN formation TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN cup_phase TEXT NOT NULL DEFAULT 'group'`,
    `ALTER TABLE matches ADD COLUMN cup_round TEXT`,
    `ALTER TABLE matches ADD COLUMN report_open INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN yellow_card INTEGER NOT NULL DEFAULT 0`,
    `ALTER TABLE match_players ADD COLUMN red_card INTEGER NOT NULL DEFAULT 0`,
    // Vem som loggade händelsen – gör duplikatskyddet per rapportör så att två
    // personer kan räkna samma statistik (t.ex. mål) utan att blockera varandra.
    `ALTER TABLE match_events ADD COLUMN reporter TEXT`,
    `ALTER TABLE player_interviews ADD COLUMN interview_type TEXT NOT NULL DEFAULT 'spelarsamtal'`,
    `ALTER TABLE player_interviews ADD COLUMN scores TEXT NOT NULL DEFAULT '{}'`,
    `ALTER TABLE players ADD COLUMN pin TEXT`,
    // Löpande form-tal (ELO) – NULL tills spelaren betygsatts första gången, då
    // det seedas från spelarens nivå. Se lib/rating.ts.
    `ALTER TABLE players ADD COLUMN form_rating INTEGER`,
    `ALTER TABLE matches ADD COLUMN cup_group TEXT NOT NULL DEFAULT ''`,
    `ALTER TABLE matches ADD COLUMN location TEXT NOT NULL DEFAULT ''`,
  ];
  for (const sql of migrations) await tryExec(sql);

  await tryExec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_matches_code ON matches(code) WHERE code IS NOT NULL`
  );
  await tryExec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_players_token ON players(share_token) WHERE share_token IS NOT NULL`
  );
  await tryExec(
    `CREATE UNIQUE INDEX IF NOT EXISTS idx_matches_uid ON matches(external_uid) WHERE external_uid IS NOT NULL`
  );

  // Seed – inställningar
  const settingsCount = await getClient().unsafe("SELECT COUNT(*) AS c FROM settings");
  if (Number(settingsCount[0].c) === 0) {
    const defaults: [string, string][] = [
      ["club_name", "Bollstanäs SK"],
      ["team_name", "BSK F2014"],
      ["birth_year", "2014"],
      ["primary_color", DEFAULT_COLORS.primary_color],
      ["accent_color", DEFAULT_COLORS.accent_color],
      ["coach_code", "TRANARE2014"],
      ["season", "2026"],
    ];
    for (const [k, v] of defaults) {
      await getClient().unsafe("INSERT INTO settings (key, value) VALUES ($1, $2)", [k, v]);
    }
  }
  await getClient().unsafe(
    "INSERT INTO settings (key, value) VALUES ('calendar_url', '') ON CONFLICT (key) DO NOTHING"
  );
  await getClient().unsafe(
    "INSERT INTO settings (key, value) VALUES ('allowed_coach_emails', '') ON CONFLICT (key) DO NOTHING"
  );
  // Matchtröjefärger – seedas för redan installerade appar utan att skriva över
  const jerseyDefaults: [string, string][] = [
    ["jersey_color", DEFAULT_COLORS.jersey_color],
    ["jersey_text_color", DEFAULT_COLORS.jersey_text_color],
    ["gk_jersey_color", DEFAULT_COLORS.gk_jersey_color],
    ["gk_jersey_text_color", DEFAULT_COLORS.gk_jersey_text_color],
  ];
  for (const [k, v] of jerseyDefaults) {
    await getClient().unsafe(
      "INSERT INTO settings (key, value) VALUES ($1, $2) ON CONFLICT (key) DO NOTHING",
      [k, v]
    );
  }

  // Seed – exempelspelare
  const playerCount = await getClient().unsafe("SELECT COUNT(*) AS c FROM players");
  if (Number(playerCount[0].c) === 0) {
    const demo = [
      "Exempel: Alva", "Exempel: Ebba", "Exempel: Elsa", "Exempel: Freja",
      "Exempel: Lilly", "Exempel: Maja", "Exempel: Nora", "Exempel: Saga",
      "Exempel: Stella", "Exempel: Vera",
    ];
    for (let i = 0; i < demo.length; i++) {
      await getClient().unsafe(
        "INSERT INTO players (name, jersey_number) VALUES ($1, $2)",
        [demo[i], i + 2]
      );
    }
  }

  // Stämpla schemat som aktuellt så nästa kalla start hoppar över allt ovan.
  await getClient().unsafe(
    "INSERT INTO settings (key, value) VALUES ('schema_version', $1) ON CONFLICT (key) DO UPDATE SET value = excluded.value",
    [SCHEMA_VERSION]
  );
}

let readyPromise: Promise<void> | null = null;
function ready(): Promise<void> {
  if (!readyPromise) readyPromise = init();
  return readyPromise;
}

// ---- Frågehjälpare ----

export async function all<T>(sqlText: string, args: SqlArgs = []): Promise<T[]> {
  await ready();
  const rows = await getClient().unsafe(toPositional(sqlText), args as never[]);
  return rows as unknown as T[];
}

export async function get<T>(sqlText: string, args: SqlArgs = []): Promise<T | undefined> {
  const rows = await all<T>(sqlText, args);
  return rows[0];
}

export async function run(sqlText: string, args: SqlArgs = []): Promise<Record<string, unknown>[]> {
  await ready();
  const rows = await getClient().unsafe(toPositional(sqlText), args as never[]);
  return rows as unknown as Record<string, unknown>[];
}

// Flera skrivningar i en transaktion
export async function batch(statements: { sql: string; args?: SqlArgs }[]): Promise<void> {
  await ready();
  if (statements.length === 0) return;
  await getClient().begin(async (tx) => {
    for (const s of statements) {
      await tx.unsafe(toPositional(s.sql), (s.args ?? []) as never[]);
    }
  });
}

// ---- Inställningar ----

export async function getSetting(key: string): Promise<string> {
  const row = await get<{ value: string }>("SELECT value FROM settings WHERE key = ?", [key]);
  return row?.value ?? "";
}

export async function setSetting(key: string, value: string): Promise<void> {
  await run(
    "INSERT INTO settings (key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value",
    [key, value]
  );
}

export async function getAllSettings(): Promise<Record<string, string>> {
  const rows = await all<{ key: string; value: string }>("SELECT key, value FROM settings");
  return Object.fromEntries(rows.map((r) => [r.key, r.value]));
}

// ---- Aktivitetslogg ----

export type ActivityEntry = {
  id: number;
  coach_name: string;
  action: string;
  subject: string;
  created_at: string;
};

export async function logActivity(coachName: string, action: string, subject: string): Promise<void> {
  await run(
    "INSERT INTO activity_log (coach_name, action, subject) VALUES (?, ?, ?)",
    [coachName.slice(0, 60), action.slice(0, 80), subject.slice(0, 100)]
  );
}

export async function getRecentActivity(limit = 10): Promise<ActivityEntry[]> {
  return all<ActivityEntry>(
    "SELECT id, coach_name, action, subject, created_at FROM activity_log ORDER BY id DESC LIMIT ?",
    [limit]
  );
}
