"""Reconcile BSK kickoffs with native Hermes one-shot jobs. No message sending here."""
from datetime import datetime, timedelta, timezone
from pathlib import Path
import fcntl
import hashlib
import json
import os
import subprocess

UTC=timezone.utc
PREFIX='BSK 24h – '
PAUSE_REASON='Matchen flyttad, inställd eller inte längre kommande i BSK.'

def reader_args(*args):
    return ['/usr/sbin/runuser','-u','bsk-hermes','--','/usr/bin/env','-i','PATH=/usr/bin:/bin','LANG=C.UTF-8',
            '/opt/bsk/hermes-mcp/.venv/bin/python','/opt/bsk/hermes-mcp/match_report.py',*args]


def read_schedule():
    r=subprocess.run(reader_args('--schedule'),capture_output=True,text=True,timeout=30)
    if r.returncode: raise RuntimeError('BSK:s matchschema kunde inte läsas. Befintliga påminnelser lämnas kvar.')
    return json.loads(r.stdout)


def reconcile(data,state,backend,script_dir,target,now):
    known=state.setdefault('matches',{})
    jobs={j['id']:j for j in backend.list_jobs(include_disabled=True)}
    by_name={j.get('name'):j for j in jobs.values()}
    desired={}
    for match in data['matches']:
        start=datetime.fromisoformat(match['kickoff']).astimezone(UTC)
        if start<=now: continue
        key=str(match['match_id'])+'-'+hashlib.sha256(start.isoformat().encode()).hexdigest()[:12]
        desired[key]=(match,start)
    # Pause superseded/deleted matches; don't alter completed runs or unrelated jobs.
    for key,item in known.items():
        job=jobs.get(item['job_id'])
        if key not in desired and job and job.get('enabled') and job.get('state') not in ('completed','error'):
            backend.pause_job(job['id'],reason=PAUSE_REASON)
    planned=[]
    for key,(match,start) in desired.items():
        name=PREFIX+key
        item=known.get(key)
        job=jobs.get(item['job_id']) if item else by_name.get(name)
        if job:
            if job.get('state')=='paused' and job.get('paused_reason')==PAUSE_REASON:
                backend.rearm_oneshot(job['id'],max(start-timedelta(hours=24),now+timedelta(seconds=15)).isoformat())
            # Existing completed/failed/paused/running jobs are never blindly repeated.
            known[key]={'job_id':job['id'],'match_id':match['match_id'],'kickoff':start.isoformat()}
            continue
        if item and backend.latest_execution(item['job_id']) is not None:
            continue  # An unknown delivery outcome must not cause a duplicate send.
        script='bsk-match-'+key+'.py'
        command=reader_args('--match',str(match['match_id']),'--expected',start.isoformat())
        content='''# Generated by the BSK match scheduler; contains no player data or credentials.
import subprocess,sys
result=subprocess.run(COMMAND,capture_output=True,text=True,timeout=30)
if result.returncode:
    raise RuntimeError("BSK-matchrapporten kunde inte hämtas. Kontrollera matchen i BSK.")
sys.stdout.write(result.stdout)
'''.replace('COMMAND',repr(command))
        script_dir.mkdir(parents=True,exist_ok=True)
        path=script_dir/script;path.write_text(content);path.chmod(0o600)
        due=start-timedelta(hours=24)
        run_at=max(due,now+timedelta(seconds=15))
        created=backend.create_job(prompt='Skicka BSK:s sparade laguppställning och kallelsesvar till Ömers privata chatt 24 timmar före match. Ingen agentskrivning eller automatisk inkallning av reserver.',
            schedule=run_at.isoformat(),name=name,script=script,no_agent=True,
            deliver=target,failure_deliver=target,enabled_toolsets=[])
        known[key]={'job_id':created['id'],'match_id':match['match_id'],'kickoff':start.isoformat()}
        planned.append({'match_id':match['match_id'],'run_at':run_at.isoformat()})
    missing=sorted(data['missing_time'])
    warning=''
    if missing and missing!=state.get('missing_time',[]):
        warning='⚠️ BSK: avsparkstid saknas eller är otydlig för följande matcher. En 24-timmarsrapport kan inte tidsättas förrän tiden är rättad:\n'+'\n'.join(f'https://bsk2014.se/matcher/{id}' for id in missing)
    state['missing_time']=missing
    return planned,warning


def main():
    from cron import jobs
    from cron.executions import latest_execution as read_latest_execution
    from hermes_constants import get_hermes_home
    class Backend:
        list_jobs=staticmethod(jobs.list_jobs)
        create_job=staticmethod(jobs.create_job)
        pause_job=staticmethod(jobs.pause_job)
        rearm_oneshot=staticmethod(jobs.rearm_oneshot)
        latest_execution=staticmethod(read_latest_execution)
    home=get_hermes_home();folder=home/'bsk-match-reports';folder.mkdir(mode=0o700,exist_ok=True)
    config=json.loads((folder/'config.json').read_text())
    if not config.get('enabled'): return
    with (folder/'reconcile.lock').open('w') as lock:
        fcntl.flock(lock,fcntl.LOCK_EX)
        statefile=folder/'state.json';state=json.loads(statefile.read_text()) if statefile.exists() else {}
        _,warning=reconcile(read_schedule(),state,Backend,home/'scripts',config['deliver'],datetime.now(UTC))
        tmp=statefile.with_suffix('.tmp');tmp.write_text(json.dumps(state,indent=2));tmp.chmod(0o600);os.replace(tmp,statefile)
        if warning: print(warning)

if __name__=='__main__': main()
